image: python:3.8-buster

variables:
  PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'

before_script:
  - 'apt-get install libpango-1.0-0 libpangoft2-1.0-0 libjpeg-dev libopenjp2-7-dev libffi-dev'
  - 'python3 -m venv venv'
  - 'source venv/bin/activate'
  - 'pip install --upgrade pip'
  - 'pip install -r requirements.txt'

cache:
  key: '$CI_COMMIT_REF_SLUG'
  paths:
    - '.cache/pip'

build:
  stage: build
  variables:
    ENABLE_PDF_EXPORT: 1
  script:
    - 'mkdocs build --verbose --site-dir build'
    - 'cp build/pdf/document.pdf documentation.pdf'
  artifacts:
    when: on_success
    paths:
      - 'documentation.pdf'

pages:
  stage: deploy
  variables:
    ENABLE_PDF_EXPORT: 0
  script:
    - 'source venv/bin/activate'
    - 'mkdocs build --verbose --site-dir public'
  artifacts:
    when: on_success
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
