site_name: Documentation Missive
site_url: https://anthony-rdrgz.docs.ictge.ch/missive
site_author: Anthony Rodriguez
site_description: >-
  Documentation de Missive, travail de diplôme d'Anthony Rodriguez, étudiant en informatique technicien ES 2023/2024

# Repository
repo_name: anthony-rdrgz/missive
repo_url: https://gitlab.ictge.ch/anthony-rdrgz/missive

# Copyright
copyright: Copyright &copy; 2023 - 2024 Anthony Rodriguez

# Configuration
theme:
  name: material
  language: fr
  custom_dir: custom_templates/
  logo: assets/img/missive_logo.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - with-pdf:
      author: Anthony Rodriguez
      credits: CFPT Informatique
      cover: true
      cover_title: Documentation Missive
      cover_subtitle: Documentation de Missive, travail de diplôme d'Anthony Rodriguez, étudiant en informatique technicien ES 2023/2024
      toc_title: Table des matières
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: pdf/anthony-rdrgz-documentation-missive.pdf
      exclude_pages: 
        - ^$
        - api
  - glightbox
  - build_plantuml:
      render: 'server'
      server: 'http://www.plantuml.com/plantuml' # official plantuml server
      output_format: 'svg' # or "png"
      diagram_root: 'docs/assets/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
  - swagger-ui-tag
# Extensions
markdown_extensions:
  - abbr
  - tables
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - stylesheets/disable-sidebar.css
  - stylesheets/inline-figures.css
  - stylesheets/increase-logo-size.css
# Page tree
nav:
  - Accueil: index.md
  - Cahier des charges: cahier-des-charges.md
  - Fonctionnement: fonctionnement.md
  - API: api.md
  - API client: https://anthony-rdrgz.docs.ictge.ch/missive/client-api
  - Plan de tests: testing.md
  - Journal de bord: journal.md
