@startuml database
entity "User" as user {
    * id : string <<generated>>
    --
    * username : text 
    * password : text
    phone_number : text
    created_at : date <<generated>>
    updated_at : date <<generated>>
}

entity "Temporary Message" as temporaryMessage {
    * id : string <<generated>>
    --
    * text : text
    * user_id : number <<FK>>
    created_at : date <<generated>>
    updated_at : date <<generated>>
}

entity "Refresh Token" as refreshToken {
    * user_id : string <<FK>>
    --
    * token : text
}

entity "PreKey" as preKey {
    * id: string <<generated>>
    --
    * user_id : string <<FK>>
    * public_key : text
}

entity "Signed PreKey" as signedPreKey {
    * id: string <<generated>>
    --
    * user_id : string <<FK>>
    * public_key : text
    * signature : text
}

user }o--|| temporaryMessage
user }o--|| refreshToken
user }o--|| preKey
user |o--|| signedPreKey
@enduml
