@startuml login-sequence
actor Utilisateur as User
entity "Application" as Client
entity API
database "Base de données" as Database

User -> Client : Création de compte
Client -> Client : Vérification des données 
alt Données client valides
    Client -> API : Envoi des informations de\n création de compte
    API -> API : Vérification des données
    alt Données serveur valides 
        API -> Database : Stockage des données de compte
        Database -> API : Confirmation de stockage
        API -> Client : Confirmation de création de compte
        Client -> Client : Génération des clés publiques et privées
        Client -> Client : Stockage de la clé privée\n(API native sécurisée)
        Client -> API : Envoi des clés publiques
        API -> Database : Stockage des clés publiques
        Database -> API : Confirmation de stockage
        API -> Client : Confirmation de stockage des clés publiques
        Client -> User : Redirection vers la page d'accueil
    else Données invalides 
        API -> Client : Erreur de création de compte
        Client -> Client : Suppression de la clé privée
        Client -> User : Informe l'utilisateur de l'erreur
    end
else Données client invalides 
    Client -> User : Informe l'utilisateur de l'erreur
end
@enduml
