
@startuml sending-message
actor "Envoyeur" as Sender
entity "Serveur WebSocket" as WebSocket
database "Base de données" as Database
actor "Destinataire" as Receiver

Sender -> WebSocket : Envoi d'un message (protocole WebSocket)
WebSocket -> WebSocket : Vérification du destinataire \n(récupération de la connexion)
alt Destinataire en ligne
    WebSocket -> Receiver : Envoi du message
    WebSocket -> Sender : Confirmation de la réception
else Destinataire hors ligne
    WebSocket -> Database : Requête d'enregistrement du message
    Database -> WebSocket : Confirmation de l'enregistrement
    WebSocket -> Receiver : Envoi d'une notification
    alt Notification reçue
        WebSocket -> Sender : Confirmation de l'envoi
    end
end
@enduml
